---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: gloomos
description: This is my personal OS image.
base-image: quay.io/fedora/fedora-silverblue
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      cleanup: true
      nonfree: rpmfusion
      copr:
       - atim/starship
      install:
        skip-unavailable: true
        packages:
        - helix
        - starship
      remove:
        packages:
        - firefox
        - firefox-langpacks
  - type: default-flatpaks
    notify: true
    system: {}
    user:
      install:
        - app.zen_browser.zen
  - type: signing